run-llama/helm-charts

- charts/llamacloud/Chart.yaml
- charts/llamacloud/values.yaml
> chore: Bump chart version to 0.1.9

- .github/workflows/helm_lint_test.yaml
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/templates/_helpers.tpl
- charts/llamacloud/templates/backend/deployment.yaml
- charts/llamacloud/templates/jobs-service/deployment.yaml
- charts/llamacloud/templates/jobs-worker/configmap.yaml
- charts/llamacloud/templates/jobs-worker/deployment.yaml
- charts/llamacloud/templates/llamaparse/deployment.yaml
- charts/llamacloud/templates/usage/deployment.yaml
- charts/llamacloud/values.yaml
Quick pr to enable setting secrets for each dependency separately.
> feat: Improve the ux of configuring individual secret objects for each dependency

- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
This pr also increases the default resource values for the postgres subchart.
> chore: Bump chart version to 0.1.14

- .github/workflows/helm_lint_test.yaml
- charts/llamacloud/ci/test-small-values.yaml
Start adding some test cases :)
> Start to add test cases to charts/llamacloud/ci

- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
Contains small fix for sync screenshot issue
> release 0.1.19

- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
to fix frontend pod crashloopbackoff
> release 0.1.21

- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
mainly trying to create a release to get [this PR out](https://github.com/run-llama/platform/commit/ad7f178989e1216239f00378eb8be5d564586756)
> release 0.1.29

- CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/templates/frontend/deployment.yaml
- charts/llamacloud/values.yaml
> release 0.1.37

- CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
still running image tagging script locally
> release 0.1.38

- .github/workflows/helm_lint_test.yaml
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
Couple of improvements:
- Updates to liveness/readiness/startup probes
- Updates to resource requests recommendations for average workloads.
- New features! Better parsing! And more!
> release: 0.1.42

- charts/llamacloud/Chart.yaml
- charts/llamacloud/templates/backend/configmap.yaml
- charts/llamacloud/templates/jobs-service/configmap.yaml
- charts/llamacloud/templates/jobs-worker/configmap.yaml
- charts/llamacloud/templates/llamaparse/deployment.yaml
- charts/llamacloud/templates/llamaparse/secret.yaml
- charts/llamacloud/tests/llamaparse_bedrock_deployment_test.yaml
- charts/llamacloud/values.yaml
This release adds AWS Bedrock support for LlamaParse. :)
> release: 0.1.44

- charts/llamacloud/Chart.yaml
- charts/llamacloud/values.yaml
> Release: 0.1.45

- .gitignore
- charts/llamacloud/docker/.env.llamacloud.template
- charts/llamacloud/docker/.env.llamaparse.template
- charts/llamacloud/docker/.env.secrets.template
- charts/llamacloud/docker/README.md
- charts/llamacloud/docker/docker-compose.yaml
- charts/llamacloud/docker/run.sh
- charts/llamacloud/docker/setup-filestore.sh
- charts/llamacloud/docker/setup-keycloak.sh
- charts/llamacloud/docker/setup.sh
- charts/llamacloud/templates/llamaparse/configmap.yaml
This pr supports running LlamaCloud via a docker-compose.yaml file (mostly local testing).
> Add docker-compose.yml support

- charts/llamacloud/README.md
- charts/llamacloud/templates/_helpers.tpl
- charts/llamacloud/templates/backend/serviceaccount.yaml
- charts/llamacloud/templates/frontend/serviceaccount.yaml
- charts/llamacloud/templates/jobs-service/serviceaccount.yaml
- charts/llamacloud/templates/jobs-worker/serviceaccount.yaml
- charts/llamacloud/templates/llamaparse-ocr/serviceaccount.yaml
- charts/llamacloud/templates/llamaparse/serviceaccount.yaml
- charts/llamacloud/templates/s3proxy/serviceaccount.yaml
- charts/llamacloud/templates/usage/serviceaccount.yaml
- charts/llamacloud/values.yaml
Allow `automountServiceAccountToken` to be changed via `values.yaml`
> feat: 🎸 allow automountServiceAccountToken to be configurable

- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
Forgot to bump the chart version in the last pr 🤦
> release: 0.1.46 and bump the chart version

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/templates/jobs-service/serviceaccount.yaml
- charts/llamacloud/templates/jobs-worker/serviceaccount.yaml
- charts/llamacloud/values.yaml
More and more improvements coming out faster and faster!
> Release 0.3.2

- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
> chore: 0.3.4

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/templates/_helpers.tpl
- charts/llamacloud/templates/llamaparse/secret.yaml
- charts/llamacloud/tests/llamaparse_test.yaml
- charts/llamacloud/values.yaml
> Release: 0.3.5

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
> Release: 0.4.1

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/templates/_helpers.tpl
- charts/llamacloud/templates/llamaparse-layout-detection-api/deployment.yaml
- charts/llamacloud/templates/llamaparse-layout-detection-api/hpa.yaml
- charts/llamacloud/templates/llamaparse-layout-detection-api/pdb.yaml
- charts/llamacloud/templates/llamaparse-layout-detection-api/service.yaml
- charts/llamacloud/templates/llamaparse-layout-detection-api/serviceaccount.yaml
- charts/llamacloud/templates/llamaparse/configmap.yaml
- charts/llamacloud/tests/llamaparse_layout_detection_api_test.yaml
- charts/llamacloud/values.yaml
> Release: 0.4.3

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/deployment_tests/index/test_index.py
- charts/llamacloud/templates/backend/deployment.yaml
- charts/llamacloud/templates/jobs-service/deployment.yaml
- charts/llamacloud/templates/jobs-worker/deployment.yaml
- charts/llamacloud/templates/llamaparse/secret.yaml
- charts/llamacloud/templates/usage/deployment.yaml
- charts/llamacloud/tests/backend_test.yaml
- charts/llamacloud/tests/jobs_service_test.yaml
- charts/llamacloud/tests/jobs_worker_test.yaml
- charts/llamacloud/tests/llamaparse_test.yaml
- charts/llamacloud/values.yaml
> Release: 0.4.4

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
> Release: 0.4.5

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/templates/_helpers.tpl
- charts/llamacloud/templates/jobs-worker/configmap.yaml
- charts/llamacloud/templates/llamaparse/secret.yaml
- charts/llamacloud/tests/backend_test.yaml
- charts/llamacloud/tests/jobs_worker_test.yaml
- charts/llamacloud/tests/llamaparse_test.yaml
- charts/llamacloud/values.yaml
> Release: 0.4.6

- .github/workflows/helm_lint_test.yaml
- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/templates/backend/configmap.yaml
- charts/llamacloud/templates/backend/deployment.yaml
- charts/llamacloud/templates/jobs-service/deployment.yaml
- charts/llamacloud/templates/jobs-worker/configmap.yaml
- charts/llamacloud/templates/llamaparse/deployment.yaml
- charts/llamacloud/tests/backend_test.yaml
- charts/llamacloud/tests/jobs_service_test.yaml
- charts/llamacloud/tests/jobs_worker_test.yaml
- charts/llamacloud/values.yaml
> Release: 0.5.2

- charts/llamacloud/CHANGELOG.md
- charts/llamacloud/Chart.yaml
- charts/llamacloud/README.md
- charts/llamacloud/values.yaml
> Release: 0.5.6
